steps:

  load-cache:
    image: drillster/drone-volume-cache
    volumes: [/var/lib/docker/tmp:/cache]
    settings:
      restore: true
      mount:
        - .gradle/caches
        - .gradle/wrapper

#  test:
#    image: openjdk:11-slim
#    commands:
#      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
#      - ./gradlew check
#    when:
#      event: [push, pull_request]

  build:
    image: openjdk:11-slim
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew build -Pbranch=$DRONE_COMMIT_BRANCH -PdeployUser=$SNAPSHOT_USER -PdeployPassword=$SNAPSHOT_PASS
    secrets: [ snapshot_user, snapshot_pass]
    when:
      event: [push, pull_request]

  build-release:
    image: openjdk:11-slim
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew build -Prelease=true -PdeployUser=$SNAPSHOT_USER -PdeployPassword=$SNAPSHOT_PASS
    secrets: [ snapshot_user, snapshot_pass]
    when:
      event: tag

  publish-snapshot:
    image: openjdk:11-slim
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew publish -Pbranch=$DRONE_COMMIT_BRANCH -PdeployUser=$SNAPSHOT_USER -PdeployPassword=$SNAPSHOT_PASS
    secrets: [ snapshot_user, snapshot_pass]
    when:
      event: push
#      branch: master

  publish-release:
    image: openjdk:11-slim
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew publish -Prelease=true -PdeployUser=$SNAPSHOT_USER -PdeployPassword=$SNAPSHOT_PASS
    secrets: [ snapshot_user, snapshot_pass]
    when:
      event: tag

  save-cache:
    image: drillster/drone-volume-cache
    volumes: [/var/lib/docker/tmp:/cache]
    settings:
      rebuild: true
      mount:
        - .gradle/caches
        - .gradle/wrapper
