package de.ii.xtraplatform.features.domain

import de.ii.xtraplatform.crs.domain.EpsgCrs

class FeatureProviderDataFixtures {

    static final FeatureProviderDataV1 ONEO_V1 = new ImmutableFeatureProviderDataV1.Builder()
            .id("oneo")
            .createdAt(1586271491161)
            .lastModified(1586271491161)
            .providerType("FEATURE")
            .featureProviderType("SQL")
            .nativeCrs(EpsgCrs.of(25832))
            .putTypes2("fundorttiere", new ImmutableFeatureType.Builder()
                    .putProperties2("id", new ImmutableFeatureProperty.Builder()
                            .path("/fundorttiere/[id=id]osirisobjekt/id")
                            .type(FeatureProperty.Type.STRING)
                            .role(FeatureProperty.Role.ID)
                    )
                    .putProperties2("foto[foto].fotoverweis", new ImmutableFeatureProperty.Builder()
                            .path("/fundorttiere/[id=id]osirisobjekt/[id=osirisobjekt_id]osirisobjekt_2_foto/[foto_id=id]foto/fotoverweis")
                            .type(FeatureProperty.Type.STRING)
                    )
                    .putProperties2("raumreferenz[raumreferenz].ortsangabe[ortsangaben].kreisSchluessel", new ImmutableFeatureProperty.Builder()
                            .path("/fundorttiere/[id=id]osirisobjekt/[id=osirisobjekt_id]osirisobjekt_2_raumreferenz/[raumreferenz_id=id]raumreferenz/[id=raumreferenz_id]raumreferenz_2_ortsangabe/[ortsangabe_id=id]ortsangaben/kreisschluessel")
                            .type(FeatureProperty.Type.STRING)
                    )
                    .putProperties2("raumreferenz[raumreferenz].ortsangabe[ortsangaben].flurstuecksKennzeichen[ortsangaben_flurstueckskennzeichen]", new ImmutableFeatureProperty.Builder()
                            .path("/fundorttiere/[id=id]osirisobjekt/[id=osirisobjekt_id]osirisobjekt_2_raumreferenz/[raumreferenz_id=id]raumreferenz/[id=raumreferenz_id]raumreferenz_2_ortsangabe/[ortsangabe_id=id]ortsangaben/[id=ortsangaben_id]ortsangaben_flurstueckskennzeichen/flurstueckskennzeichen")
                            .type(FeatureProperty.Type.STRING)
                    )
                    .putProperties2("raumreferenz[raumreferenz].datumAbgleich", new ImmutableFeatureProperty.Builder()
                            .path("/fundorttiere/[id=id]osirisobjekt/[id=osirisobjekt_id]osirisobjekt_2_raumreferenz/[raumreferenz_id=id]raumreferenz/datumabgleich")
                            .type(FeatureProperty.Type.STRING)
                    )
                    .putProperties2("raumreferenz[raumreferenz].fachreferenz[raumreferenz_2_fachreferenz]", new ImmutableFeatureProperty.Builder()
                            .path("/fundorttiere/[id=id]osirisobjekt/[id=osirisobjekt_id]osirisobjekt_2_raumreferenz/[raumreferenz_id=id]raumreferenz/[id=raumreferenz_id]raumreferenz_2_fachreferenz/objektart:fachreferenz_id")
                            .type(FeatureProperty.Type.STRING)
                    )
            )
            .build()



    static final FeatureProviderDataV2 ONEO_V2 = new ImmutableFeatureProviderDataV2.Builder()
            .id("oneo")
            .createdAt(1586271491161)
            .lastModified(1586271491161)
            .providerType("FEATURE")
            .featureProviderType("SQL")
            .nativeCrs(EpsgCrs.of(25832))
            .putTypes2("fundorttiere", new ImmutableFeatureTypeV2.Builder()
            .path("/fundorttiere")
                    .putProperties2("id", new ImmutableFeaturePropertyV2.Builder()
                            .path("[id=id]osirisobjekt/id")
                            .type(FeatureSchema.Type.STRING)
                            .role(FeatureSchema.Role.ID)
                    )
                    .putProperties2("foto", new ImmutableFeaturePropertyV2.Builder()
                            .path("[id=id]osirisobjekt/[id=osirisobjekt_id]osirisobjekt_2_foto/[foto_id=id]foto")
                            .type(FeatureSchema.Type.OBJECT_ARRAY)
                            .putProperties2("fotoverweis", new ImmutableFeaturePropertyV2.Builder()
                                    .path("fotoverweis")
                                    .type(FeatureSchema.Type.STRING)
                            )
                    )
                    .putProperties2("raumreferenz", new ImmutableFeaturePropertyV2.Builder()
                            .path("[id=id]osirisobjekt/[id=osirisobjekt_id]osirisobjekt_2_raumreferenz/[raumreferenz_id=id]raumreferenz")
                            .type(FeatureSchema.Type.OBJECT_ARRAY)
                            .putProperties2("ortsangabe", new ImmutableFeaturePropertyV2.Builder()
                                    .path("[id=raumreferenz_id]raumreferenz_2_ortsangabe/[ortsangabe_id=id]ortsangaben")
                                    .type(FeatureSchema.Type.OBJECT_ARRAY)
                                    .putProperties2("kreisSchluessel", new ImmutableFeaturePropertyV2.Builder()
                                            .path("kreisschluessel")
                                            .type(FeatureSchema.Type.STRING)
                                    )
                                    .putProperties2("flurstuecksKennzeichen", new ImmutableFeaturePropertyV2.Builder()
                                            .path("[id=ortsangaben_id]ortsangaben_flurstueckskennzeichen/flurstueckskennzeichen")
                                            .type(FeatureSchema.Type.VALUE_ARRAY)
                                            .valueType(FeatureSchema.Type.STRING)
                                    )
                            )
                            .putProperties2("datumAbgleich", new ImmutableFeaturePropertyV2.Builder()
                                    .path("datumabgleich")
                                    .type(FeatureSchema.Type.STRING)
                            )
                            .putProperties2("fachreferenz", new ImmutableFeaturePropertyV2.Builder()
                                    .path("[id=raumreferenz_id]raumreferenz_2_fachreferenz/objektart:fachreferenz_id")
                                    .type(FeatureSchema.Type.VALUE_ARRAY)
                                    .valueType(FeatureSchema.Type.STRING)
                            )
                    )
            )
            .build()
}
